# Generated by Django 4.2.4 on 2023-09-02 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('hash', models.TextField(verbose_name='Hash')),
                ('assinatura', models.BinaryField(verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Assinaturas do Usuário',
                'verbose_name_plural': 'Assinaturas do Usuários',
            },
        ),
        migrations.CreateModel(
            name='UserDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('salvo', models.BooleanField(verbose_name='Foi salvo?')),
                ('assinado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturaUser', to='KeySigned_app.userassinatura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDocumento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento do Usuário',
                'verbose_name_plural': 'Documentos do Usuários',
            },
        ),
        migrations.CreateModel(
            name='UserChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_privada', models.BinaryField(verbose_name='Chave Privada')),
                ('chave_publica', models.BinaryField(verbose_name='Chave Pública')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userChave', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chave do Usuário',
                'verbose_name_plural': 'Chave do Usuários',
            },
        ),
    ]
